#!/usr/bin/python3

import requests, json, os, sys

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/cfginfo"

response = requests.get(url)

if(response.status_code == 200):
    return_data = response.json()
    print("Success: " + return_data["files"])
else:
    print("Failure: Have better error checking than this sample pls")


# print("tiny-1-1.cfg")
# print("tiny-2-2.cfg")
# print("tiny-3-3.cfg")
