#!/usr/bin/python3

HOSTNAME = "localhost"
PORT = "8080"

url = "http://" + HOSTNAME + ":" + PORT + "/destroyall/"

response = requests.delete(url)

if(response.status_code == 200):
    print("Success!")
else:
    print("Failure!")





